import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

import { Montserrat, Roboto, Lato } from 'next/font/google';
import Articles from '@/components/Articles'
const inter = Inter({ 
  subsets: ['latin'], 
  display:'swap' 
});

const montserrat = Montserrat({
  weight: '800',
  subsets: ['latin'],
  display: 'swap',
})

const lato = Lato({
  weight: '700',
  subsets: ['latin'],
  display: 'swap',
})

const roboto = Roboto({
  weight: '700',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${montserrat.className} ${roboto.className} ${lato.className}`}>
      <body className={inter.className}>
        <Header/>
        <Articles/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
